// The Ordinary of the Mass, Missale Romanum 1962 (Low Mass), and every change made to it
// by 1970. Facts: docs/research/change-table.md. English of both missals is our own
// translation from the Latin; scripture follows the Douay-Rheims (Challoner).

const src = (vetus, novus, stage, note = "", confidence = "high") => ({ vetus, novus, stage, note, confidence });

const blk = (kind) => (id, text, extra = {}) => ({ id, kind, text, ...extra });
const R = blk("rubric");
const H = blk("heading");
const X = blk("scripture");
const Pr = blk("prayer");
const P = (id, text, extra = {}) => ({ id, kind: "versicle", speaker: "P", text, ...extra });
const S = (id, text, extra = {}) => ({ id, kind: "response", speaker: "S", text, ...extra });
// Lines of the 1970 text on the pasted scraps.
const n = (id, text, speaker) => ({ id, kind: speaker ? "versicle" : "prayer", text, ...(speaker ? { speaker } : {}) });
const nr = (id, text) => ({ id, kind: "rubric", text });
const nh = (id, text) => ({ id, kind: "heading", text });

const OM62 = "Missale Romanum 1962, Ordo Missae";
const RS62 = "Missale Romanum 1962, Ritus servandus";
const OM70 = "Missale Romanum 1970, Ordo Missae";
const ABSENT = `${OM70}: absent`;
const IO = (k) => `1964 (Inter Oecumenici ${k})`;
const TAA = (k) => `1967 (Tres abhinc annos ${k})`;

const foot = {
  id: "foot", title: "Prayers at the Foot of the Altar", initial: "I",
  blocks: [
    R("foot.r1", "The Priest, having made due reverence to the altar, stands at its foot, signs himself from forehead to breast, and says in a clear voice:"),
    Pr("foot.1", "In the name of the Father, ✠ and of the Son, and of the Holy Ghost. Amen.", { postures: ["sign-cross"] }),
    P("foot.2", "I will go in unto the altar of God."),
    S("foot.3", "To God, who giveth joy to my youth."),
    P("foot.ps1", "Judge me, O God, and distinguish my cause from the nation that is not holy: deliver me from the unjust and deceitful man."),
    S("foot.ps2", "For thou art God my strength: why hast thou cast me off? and why do I go sorrowful whilst the enemy afflicteth me?"),
    P("foot.ps3", "Send forth thy light and thy truth: they have conducted me, and brought me unto thy holy hill, and into thy tabernacles."),
    S("foot.ps4", "And I will go in to the altar of God: to God who giveth joy to my youth."),
    P("foot.ps5", "To thee, O God my God, I will give praise upon the harp: why art thou sad, O my soul? and why dost thou disquiet me?"),
    S("foot.ps6", "Hope in God, for I will still give praise to him: the salvation of my countenance, and my God."),
    P("foot.ps7", "Glory be to the Father, and to the Son, and to the Holy Ghost.", { postures: ["bow-head"] }),
    S("foot.ps8", "As it was in the beginning, is now, and ever shall be, world without end. Amen."),
    P("foot.ps9", "I will go in unto the altar of God."),
    S("foot.ps10", "To God, who giveth joy to my youth."),
    P("foot.adj1", "Our help ✠ is in the name of the Lord.", { postures: ["sign-cross"] }),
    S("foot.adj2", "Who made heaven and earth."),
    R("foot.r2", "Bowing low, with hands joined, the Priest makes the Confession:"),
    P("foot.conf", "I confess to almighty God, to blessed Mary ever Virgin, to blessed Michael the Archangel, to blessed John the Baptist, to the holy Apostles Peter and Paul, to all the Saints, and to you, brethren, that I have sinned exceedingly in thought, word and deed: through my fault, through my fault, through my most grievous fault. Therefore I beseech blessed Mary ever Virgin, blessed Michael the Archangel, blessed John the Baptist, the holy Apostles Peter and Paul, all the Saints, and you, brethren, to pray for me to the Lord our God.", { postures: ["bow-profound", "strike-breast"] }),
    S("foot.mis1", "May almighty God have mercy upon thee, forgive thee thy sins, and bring thee to life everlasting."),
    P("foot.mis1a", "Amen."),
    S("foot.conf2", "I confess to almighty God, to blessed Mary ever Virgin, to blessed Michael the Archangel, to blessed John the Baptist, to the holy Apostles Peter and Paul, to all the Saints, and to thee, father, that I have sinned exceedingly in thought, word and deed: through my fault, through my fault, through my most grievous fault. Therefore I beseech blessed Mary ever Virgin, blessed Michael the Archangel, blessed John the Baptist, the holy Apostles Peter and Paul, all the Saints, and thee, father, to pray for me to the Lord our God.", { postures: ["strike-breast"] }),
    P("foot.mis2", "May almighty God have mercy upon you, forgive you your sins, and bring you to life everlasting."),
    S("foot.mis2a", "Amen."),
    P("foot.ind", "May the almighty and merciful Lord grant us pardon, ✠ absolution and remission of our sins.", { postures: ["sign-cross"] }),
    S("foot.ind2", "Amen."),
    P("foot.v1", "Thou wilt turn, O God, and bring us to life."),
    S("foot.v2", "And thy people shall rejoice in thee."),
    P("foot.v3", "Shew us, O Lord, thy mercy."),
    S("foot.v4", "And grant us thy salvation."),
    P("foot.v5", "O Lord, hear my prayer."),
    S("foot.v6", "And let my cry come unto thee."),
    P("foot.v7", "The Lord be with you."),
    S("foot.v8", "And with thy spirit."),
    R("foot.r3", "Extending and then joining his hands, he says: Let us pray. Then, going up to the altar, he says silently:"),
    Pr("foot.aufer", "Take away from us our iniquities, we beseech thee, O Lord, that with pure minds we may be found worthy to enter into the Holy of Holies. Through Christ our Lord. Amen."),
    R("foot.r4", "Bowing over the altar, his hands joined upon it, he says:"),
    Pr("foot.oramus", "We beseech thee, O Lord, by the merits of thy Saints whose relics lie here, and of all the Saints, that thou wouldst deign to pardon me all my sins. Amen."),
    R("foot.r5", "He kisses the altar in the middle."),
  ],
  edits: [
    { id: "foot-greeting", type: "added", target: "foot.1",
      replacement: [
        nh("foot-greeting.h", "Greeting · one of three"),
        n("foot-greeting.1", "The grace of our Lord Jesus Christ, the charity of God, and the fellowship of the Holy Spirit be with you all.", "P"),
        n("foot-greeting.2", "Or: Grace to you and peace from God our Father and the Lord Jesus Christ.", "P"),
        n("foot-greeting.3", "Or: The Lord be with you.", "P"),
        n("foot-greeting.4", "And with your spirit.", "R"),
      ],
      source: src("—", `${OM70}, Ritus initiales`, "1970", "A greeting to the people, in one of three forms, follows the sign of the Cross.") },
    { id: "foot-psalm", type: "removed", target: "foot.2",
      targets: ["foot.3", "foot.ps1", "foot.ps2", "foot.ps3", "foot.ps4", "foot.ps5", "foot.ps6", "foot.ps7", "foot.ps8", "foot.ps9", "foot.ps10"],
      mark: "omit",
      source: src(`${OM62}, Ps. 42 Iudica me`, ABSENT, IO("48c"), "Antiphon Introibo and Psalm 42 with its Gloria Patri, said by priest and server at the foot of the altar.") },
    { id: "foot-adj", type: "removed", target: "foot.adj1", targets: ["foot.adj2"],
      source: src(`${OM62}, Adiutorium nostrum`, ABSENT, "1970") },
    { id: "foot-conf-saints1", type: "shortened", target: "foot.conf",
      phrase: "to blessed Mary ever Virgin, to blessed Michael the Archangel, to blessed John the Baptist, to the holy Apostles Peter and Paul, to all the Saints, ",
      source: src(`${OM62}, Confiteor`, `${OM70}, Actus paenitentialis (Confiteor)`, "1970", "In the first half, the confession is made to God and to the brethren only.") },
    { id: "foot-conf-saints2", type: "shortened", target: "foot.conf",
      phrase: "blessed Michael the Archangel, blessed John the Baptist, the holy Apostles Peter and Paul, ",
      source: src(`${OM62}, Confiteor`, `${OM70}, Confiteor`, "1970", "Blessed Mary, the angels and the saints remain in the second half; the four named saints do not.") },
    { id: "foot-conf-omission", type: "added", target: "foot.conf",
      replacement: [n("foot-conf-omission.1", "…in thought, word, deed and omission.")],
      source: src("—", `${OM70}, Confiteor`, "1970", "“et omissione” added to the list of ways one has sinned.") },
    { id: "foot-conf-bow", type: "posture", target: "foot.conf", icon: "bow-profound", action: "remove",
      source: src(`${RS62}, Confiteor`, `${OM70}: no bow prescribed`, "1970", "Striking the breast at “mea culpa” is kept.", "medium") },
    { id: "foot-conf-forms", type: "optional", target: "foot.conf", options: ["I", "II", "III"],
      replacement: [
        nh("foot-conf-forms.h", "Penitential Act · or"),
        n("foot-conf-forms.1", "II. Have pity on us, Lord. — Because we have sinned against you. Show us, Lord, your mercy. — And give us your salvation."),
        n("foot-conf-forms.2", "III. Invocations addressed to Christ, each answered “Lord, have mercy” or “Christ, have mercy”."),
      ],
      source: src(`${OM62}, Confiteor`, `${OM70}, Actus paenitentialis`, "1970", "The Confiteor becomes one of three forms of the Penitential Act.") },
    { id: "foot-conf-twice", type: "repetition", target: "foot.conf2",
      phrase: "I confess to almighty God, to blessed Mary ever Virgin, to blessed Michael the Archangel, to blessed John the Baptist, to the holy Apostles Peter and Paul, to all the Saints, and to thee, father, that I have sinned exceedingly in thought, word and deed: through my fault, through my fault, through my most grievous fault. Therefore I beseech blessed Mary ever Virgin, blessed Michael the Archangel, blessed John the Baptist, the holy Apostles Peter and Paul, all the Saints, and thee, father, to pray for me to the Lord our God.",
      mark: "1x",
      source: src(`${OM62}, Confiteor (server)`, `${OM70}, Confiteor said once by all`, "1970", "Said once, by priest and people together, instead of by the priest and then the server.") },
    { id: "foot-mis1", type: "removed", target: "foot.mis1", targets: ["foot.mis1a"],
      source: src(`${OM62}, Misereatur (server to priest)`, ABSENT, "1970", "The server's prayer for the priest goes with the second Confiteor; the priest's Misereatur for all is kept.") },
    { id: "foot-ind", type: "removed", target: "foot.ind", targets: ["foot.ind2"],
      source: src(`${OM62}, Indulgentiam`, ABSENT, "1970") },
    { id: "foot-versicles", type: "removed", target: "foot.v1", targets: ["foot.v2", "foot.v3", "foot.v4", "foot.v5", "foot.v6", "foot.v7", "foot.v8"],
      source: src(`${OM62}, Deus, tu conversus; Ostende nobis; Domine, exaudi`, ABSENT, "1970") },
    { id: "foot-aufer", type: "removed", target: "foot.r3", targets: ["foot.aufer"],
      source: src(`${OM62}, Aufer a nobis`, ABSENT, "1970") },
    { id: "foot-oramus", type: "removed", target: "foot.r4", targets: ["foot.oramus"],
      source: src(`${OM62}, Oramus te`, ABSENT, "1970", "The altar is still kissed at the start of Mass, without this prayer.") },
  ],
};

const kyrie = {
  id: "kyrie", title: "Introit, Kyrie and Gloria", initial: "G",
  blocks: [
    R("ky.r1", "The Priest goes to the Epistle side and reads the Introit of the day, signing himself at its beginning. Then, at the middle of the altar, he says the Kyrie alternately with the server:"),
    P("ky.1", "Lord, have mercy."), S("ky.2", "Lord, have mercy."), P("ky.3", "Lord, have mercy."),
    S("ky.4", "Christ, have mercy."), P("ky.5", "Christ, have mercy."), S("ky.6", "Christ, have mercy."),
    P("ky.7", "Lord, have mercy."), S("ky.8", "Lord, have mercy."), P("ky.9", "Lord, have mercy."),
    R("ky.r2", "Then, when it is to be said, extending, raising and joining his hands, he says the Gloria:"),
    Pr("ky.gloria", "Glory be to God on high, and on earth peace to men of good will. We praise thee; we bless thee; we adore thee; we glorify thee. We give thee thanks for thy great glory. O Lord God, heavenly King, God the Father almighty. O Lord Jesus Christ, the only-begotten Son. O Lord God, Lamb of God, Son of the Father, who takest away the sins of the world, have mercy on us. Who takest away the sins of the world, receive our prayer. Who sittest at the right hand of the Father, have mercy on us. For thou alone art holy; thou alone art Lord; thou alone, O Jesus Christ, art most high, together with the Holy Ghost, ✠ in the glory of God the Father. Amen."),
    R("ky.r3", "He kisses the altar and, turning to the people, says:"),
    P("ky.dv", "The Lord be with you."), S("ky.dv2", "And with thy spirit."),
    R("ky.r4", "He reads the Collect of the day."),
  ],
  edits: [
    { id: "ky-3", type: "repetition", target: "ky.3", phrase: "Lord, have mercy.",
      source: src(`${OM62}, Kyrie (ninefold)`, `${OM70}, Kyrie; GIRM 1969 on the Kyrie`, "1970", "Each acclamation is normally said twice, not three times.") },
    { id: "ky-6", type: "repetition", target: "ky.6", phrase: "Christ, have mercy.",
      source: src(`${OM62}, Kyrie (ninefold)`, `${OM70}, Kyrie`, "1970") },
    { id: "ky-9", type: "repetition", target: "ky.9", phrase: "Lord, have mercy.",
      source: src(`${OM62}, Kyrie (ninefold)`, `${OM70}, Kyrie`, "1970") },
    { id: "ky-kiss", type: "rubric", target: "ky.r3", phrase: "He kisses the altar and,",
      source: src(`${RS62}, before Dominus vobiscum`, "Altar kissed only at the beginning and end of Mass", TAA(8)) },
  ],
};

const readings = {
  id: "readings", title: "The Epistle and Gospel", initial: "C",
  blocks: [
    R("rd.r1", "The Epistle of the day is read. At its end the server answers: Thanks be to God. The Gradual, Alleluia or Tract follows."),
    R("rd.r2", "At the middle of the altar, raising his eyes and then bowing low, the Priest says silently:"),
    Pr("rd.munda", "Cleanse my heart and my lips, O almighty God, who didst cleanse the lips of the prophet Isaias with a burning coal: of thy gracious mercy so deign to cleanse me, that I may be able worthily to proclaim thy holy Gospel. Through Christ our Lord. Amen.", { postures: ["bow-profound"] }),
    Pr("rd.iube", "Pray, Lord, a blessing. The Lord be in my heart and on my lips, that I may worthily and fittingly proclaim his Gospel. Amen."),
    P("rd.dv", "The Lord be with you."), S("rd.dv2", "And with thy spirit."),
    P("rd.seq", "The continuation ✠ of the holy Gospel according to N.", { postures: ["sign-cross"] }),
    S("rd.seq2", "Glory be to thee, O Lord."),
    R("rd.r3", "The Gospel of the day is read. At its end the server answers: Praise be to thee, O Christ. The Priest kisses the book, saying: By the words of the Gospel may our sins be blotted out."),
  ],
  edits: [
    { id: "rd-readings", type: "added", target: "rd.r1",
      replacement: [
        nh("rd-readings.h", "Liturgy of the Word"),
        nr("rd-readings.1", "First Reading, usually from the Old Testament, read by a reader."),
        nr("rd-readings.2", "Responsorial Psalm."),
        nr("rd-readings.3", "Second Reading, on Sundays and solemnities."),
      ],
      source: src(`${OM62}, Epistola`, `${OM70}, Liturgia verbi`, "1970", "Readings arranged in a new lectionary (three-year Sunday cycle, 1969); the readings themselves are Propers and not shown.") },
    { id: "rd-munda-isaias", type: "shortened", target: "rd.munda",
      phrase: " who didst cleanse the lips of the prophet Isaias with a burning coal: of thy gracious mercy so deign to cleanse me,",
      source: src(`${OM62}, Munda cor meum`, `${OM70}, Munda cor meum`, "1970", "Reduced to: cleanse my heart and my lips, almighty God, that I may worthily proclaim your holy Gospel.") },
    { id: "rd-munda-concl", type: "shortened", target: "rd.munda", phrase: " Through Christ our Lord. Amen.",
      source: src(`${OM62}, Munda cor meum`, `${OM70}, Munda cor meum`, "1970") },
    { id: "rd-iube", type: "removed", target: "rd.iube",
      source: src(`${OM62}, Iube, Domine, benedicere`, `${OM70}: the blessing is asked only by a deacon`, "1970", "", "medium") },
    { id: "rd-homily", type: "added", target: "rd.r3",
      replacement: [nh("rd-homily.h", "Homily"), nr("rd-homily.1", "Required on Sundays and holy days of obligation.")],
      source: src("Sermon customary, but outside the rubrics of the Ordo", "GIRM 1969, on the homily", "1970", "Preaching existed before 1970; what is new is its place within the rite.", "medium") },
  ],
};

const creed = {
  id: "creed", title: "The Creed", initial: "I",
  blocks: [
    R("cr.r1", "On Sundays and certain feasts, at the middle of the altar, extending, raising and joining his hands, the Priest says:"),
    Pr("cr.1", "I believe in one God, the Father almighty, maker of heaven and earth, and of all things visible and invisible. And in one Lord Jesus Christ, the only-begotten Son of God, born of the Father before all ages; God of God, Light of Light, true God of true God; begotten, not made; consubstantial with the Father, by whom all things were made. Who for us men, and for our salvation, came down from heaven."),
    Pr("cr.2", "And was incarnate by the Holy Ghost of the Virgin Mary: and was made man.", { postures: ["genuflect"] }),
    Pr("cr.3", "He was crucified also for us, suffered under Pontius Pilate, and was buried. And on the third day he rose again according to the Scriptures; and ascended into heaven, and sitteth at the right hand of the Father; and he shall come again with glory to judge the living and the dead; of whose kingdom there shall be no end. And in the Holy Ghost, the Lord and Giver of life, who proceedeth from the Father and the Son; who together with the Father and the Son is adored and glorified; who spoke by the Prophets. And one holy, catholic and apostolic Church. I confess one baptism for the remission of sins. And I look for the resurrection of the dead, ✠ and the life of the world to come. Amen."),
  ],
  edits: [
    { id: "cr-incarnatus", type: "posture", target: "cr.2", icon: "genuflect", action: "change", to: "bow-profound",
      source: src(`${RS62}, Credo`, `${OM70}, Credo rubric`, "1970", "All bow; on Christmas and the Annunciation all genuflect.") },
    { id: "cr-faithful", type: "added", target: "cr.3",
      replacement: [
        nh("cr-faithful.h", "Prayer of the Faithful"),
        nr("cr-faithful.1", "Intentions are announced for the Church, for those who govern and for the salvation of the world, for all in any need, and for the local community; the people answer each one."),
      ],
      source: src("—", `${OM70}, Oratio universalis`, "1964/1970", "First restored by Inter Oecumenici 56 (1964).") },
  ],
};

const offertory = {
  id: "offertory", title: "The Offertory", initial: "R",
  blocks: [
    P("of.dv", "The Lord be with you."), S("of.dv2", "And with thy spirit."),
    R("of.r1", "He reads the Offertory verse of the day. Then, holding the paten with the host, he offers it, saying:"),
    Pr("of.suscipe", "Receive, O holy Father, almighty and eternal God, this spotless host, which I, thy unworthy servant, offer unto thee, my living and true God, for my countless sins, offences and negligences, and for all here present; and also for all faithful Christians, living and dead: that it may avail both me and them unto salvation in life everlasting. Amen."),
    R("of.r2", "Then, making the sign of the Cross with the paten, he places the host upon the corporal. Pouring wine and water into the chalice, he blesses the water, saying:"),
    Pr("of.deus", "O God, ✠ who didst wonderfully establish the dignity of human nature, and still more wonderfully restore it: grant that, by the mystery of this water and wine, we may come to share in his divinity, who deigned to share in our humanity, Jesus Christ thy Son, our Lord: who liveth and reigneth with thee in the unity of the Holy Ghost, God, world without end. Amen."),
    R("of.r3", "He offers the chalice, saying:"),
    Pr("of.offerimus", "We offer unto thee, O Lord, the chalice of salvation, beseeching thy clemency, that it may rise in the sight of thy divine Majesty, with a sweet fragrance, for our salvation and for that of the whole world. Amen."),
    R("of.r4", "He makes the sign of the Cross with the chalice and places it upon the corporal. Then, bowing, with hands joined upon the altar, he says:"),
    Pr("of.spiritu", "In a spirit of humility and with a contrite heart may we be received by thee, O Lord; and so may our sacrifice be offered in thy sight this day, that it may be pleasing unto thee, O Lord God."),
    R("of.r5", "Raising his eyes and hands, then joining them, he blesses the offerings, saying:"),
    Pr("of.veni", "Come, O Sanctifier, almighty and eternal God, and bless ✠ this sacrifice prepared for the glory of thy holy name."),
    R("of.r6", "He washes his fingers, saying:"),
    X("of.lav1", "I will wash my hands among the innocent: and will compass thy altar, O Lord: That I may hear the voice of thy praise: and tell of all thy wondrous works."),
    X("of.lav2", "I have loved, O Lord, the beauty of thy house; and the place where thy glory dwelleth. Take not away my soul, O God, with the wicked: nor my life with bloody men: In whose hands are iniquities: their right hand is filled with gifts."),
    X("of.lav3", "But as for me, I have walked in my innocence: redeem me, and have mercy on me. My foot hath stood in the direct way: in the churches I will bless thee, O Lord."),
    X("of.lav4", "Glory be to the Father, and to the Son, and to the Holy Ghost. As it was in the beginning, is now, and ever shall be, world without end. Amen."),
    R("of.r7", "Bowing slightly at the middle of the altar, with hands joined upon it, he says:"),
    Pr("of.trinitas", "Receive, O holy Trinity, this offering which we make to thee in memory of the Passion, Resurrection and Ascension of our Lord Jesus Christ, and in honour of blessed Mary ever Virgin, of blessed John the Baptist, of the holy Apostles Peter and Paul, of these and of all the Saints: that it may avail unto their honour and our salvation; and may they whose memory we keep on earth deign to intercede for us in heaven. Through the same Christ our Lord. Amen."),
    R("of.r8", "He kisses the altar, turns to the people, and says:"),
    P("of.orate", "Pray, brethren, that my sacrifice and yours may be acceptable to God the Father almighty."),
    S("of.suscipiat", "May the Lord receive the sacrifice at thy hands, to the praise and glory of his name, for our good, and that of all his holy Church."),
    R("of.r9", "He then reads the Secret prayer of the day in a low voice."),
  ],
  edits: [
    { id: "of-suscipe", type: "rewritten", target: "of.suscipe",
      replacement: [
        n("of-suscipe.1", "Blessed are you, Lord, God of the universe, for from your bounty we have received the bread which we offer you, fruit of the earth and of human labour; from it shall be made for us the bread of life.", "P"),
        n("of-suscipe.2", "Blessed be God for ever.", "R"),
      ],
      source: src(`${OM62}, Suscipe, sancte Pater`, `${OM70}, Benedictus es, Domine (panis)`, "1970") },
    { id: "of-paten-cross", type: "rubric", target: "of.r2", phrase: "making the sign of the Cross with the paten, ",
      source: src(`${RS62}, Offertory`, ABSENT, TAA(9)) },
    { id: "of-water-blessing", type: "rubric", target: "of.r2", phrase: ", he blesses the water",
      source: src(`${RS62}, Offertory`, `${OM70}: water poured without a blessing`, "1970", "", "medium") },
    { id: "of-deus-start", type: "shortened", target: "of.deus",
      phrase: "O God, ✠ who didst wonderfully establish the dignity of human nature, and still more wonderfully restore it: grant that, ",
      source: src(`${OM62}, Deus, qui humanae substantiae`, `${OM70}, Per huius aquae et vini mysterium`, "1970", "Only the central clause survives, said quietly.") },
    { id: "of-deus-end", type: "shortened", target: "of.deus",
      phrase: ", Jesus Christ thy Son, our Lord: who liveth and reigneth with thee in the unity of the Holy Ghost, God, world without end. Amen.",
      source: src(`${OM62}, Deus, qui humanae substantiae`, `${OM70}, Per huius aquae et vini mysterium`, "1970") },
    { id: "of-offerimus", type: "rewritten", target: "of.offerimus",
      replacement: [
        n("of-offerimus.1", "Blessed are you, Lord, God of the universe, for from your bounty we have received the wine which we offer you, fruit of the vine and of human labour; from it shall be made for us a spiritual drink.", "P"),
        n("of-offerimus.2", "Blessed be God for ever.", "R"),
      ],
      source: src(`${OM62}, Offerimus tibi, Domine`, `${OM70}, Benedictus es, Domine (vinum)`, "1970") },
    { id: "of-chalice-cross", type: "rubric", target: "of.r4", phrase: "He makes the sign of the Cross with the chalice and places it upon the corporal.",
      source: src(`${RS62}, Offertory`, ABSENT, TAA(9)) },
    { id: "of-veni", type: "removed", target: "of.r5", targets: ["of.veni"],
      source: src(`${OM62}, Veni, Sanctificator`, ABSENT, "1970") },
    { id: "of-lavabo", type: "rewritten", target: "of.lav1",
      replacement: [n("of-lavabo.1", "Wash me, Lord, from my iniquity, and cleanse me from my sin.", "P")],
      source: src(`${OM62}, Lavabo (Ps. 25:6–12)`, `${OM70}, Lava me, Domine`, "1970", "One verse of Psalm 50 replaces seven verses of Psalm 25 and the Gloria Patri.") },
    { id: "of-lavabo-rest", type: "removed", target: "of.lav2", targets: ["of.lav3", "of.lav4"],
      source: src(`${OM62}, Lavabo (Ps. 25:6–12)`, `${OM70}, Lava me, Domine`, "1970") },
    { id: "of-trinitas", type: "removed", target: "of.r7", targets: ["of.trinitas"],
      source: src(`${OM62}, Suscipe, sancta Trinitas`, ABSENT, "1970") },
    { id: "of-kiss", type: "rubric", target: "of.r8", phrase: "He kisses the altar, ",
      source: src(`${RS62}, Orate fratres`, "Altar kissed only at the beginning and end of Mass", TAA(8)) },
    { id: "of-secret", type: "rubric", target: "of.r9", phrase: " in a low voice",
      source: src(`${OM62}, Secreta`, `${OM70}, Oratio super oblata, said aloud`, IO("48e")) },
  ],
};

const preface = {
  id: "preface", title: "The Preface", initial: "I",
  blocks: [
    P("pf.1", "World without end."), S("pf.2", "Amen."),
    P("pf.3", "The Lord be with you."), S("pf.4", "And with thy spirit."),
    P("pf.5", "Lift up your hearts."), S("pf.6", "We have lifted them up unto the Lord."),
    P("pf.7", "Let us give thanks to the Lord our God."), S("pf.8", "It is meet and just."),
    Pr("pf.9", "It is truly meet and just, right and profitable to salvation, that we should at all times and in all places give thanks unto thee, O holy Lord, Father almighty, eternal God, through Christ our Lord: through whom the Angels praise thy majesty, the Dominations worship it, the Powers stand in awe; the heavens and the hosts of heaven and the blessed Seraphim join together in exultation to celebrate it. With these we pray thee let our voices also be admitted, as we say in humble praise:"),
    R("pf.r1", "Bowing moderately, with hands joined, he says:"),
    Pr("pf.sanctus", "Holy, Holy, Holy, Lord God of Hosts. Heaven and earth are full of thy glory. Hosanna in the highest. Blessed ✠ is he that cometh in the name of the Lord. Hosanna in the highest.", { postures: ["bow-head"] }),
  ],
  edits: [],
};

const canon = {
  id: "canon", title: "The Canon of the Mass", initial: "T",
  blocks: [
    R("cn.r1", "Raising his eyes and hands, then joining them and bowing low, the Priest says silently:"),
    Pr("cn.te", "Therefore, most merciful Father, we humbly pray and beseech thee, through Jesus Christ thy Son, our Lord, that thou wouldst accept and bless these ✠ gifts, these ✠ offerings, these ✠ holy and unblemished sacrifices, which we offer thee first for thy holy Catholic Church: deign to grant her peace, to guard, unite and govern her throughout the whole world, together with thy servant N. our Pope, N. our Bishop, and all who hold and teach the Catholic and apostolic faith.", { postures: ["bow-profound"] }),
    Pr("cn.memento", "Remember, O Lord, thy servants and handmaids N. and N., and all here present, whose faith and devotion are known unto thee; for whom we offer, or who offer unto thee, this sacrifice of praise for themselves and all who are theirs, for the redemption of their souls, for the hope of their salvation and safety; and who render their vows to thee, the eternal God, living and true."),
    Pr("cn.communicantes", "In communion with, and venerating the memory, first, of the glorious ever-Virgin Mary, Mother of our God and Lord Jesus Christ; and also of blessed Joseph, her Spouse; and of thy blessed Apostles and Martyrs, Peter and Paul, Andrew, James, John, Thomas, James, Philip, Bartholomew, Matthew, Simon and Thaddeus; Linus, Cletus, Clement, Sixtus, Cornelius, Cyprian, Lawrence, Chrysogonus, John and Paul, Cosmas and Damian, and of all thy Saints: by whose merits and prayers grant that we may in all things be defended by the help of thy protection. Through the same Christ our Lord. Amen."),
    R("cn.r2", "Spreading his hands over the offerings, he says:"),
    Pr("cn.hanc", "This offering, therefore, of our service and of thy whole family, we beseech thee, O Lord, graciously to accept; and to order our days in thy peace, and to command that we be rescued from eternal damnation and numbered in the flock of thine elect. Through Christ our Lord. Amen."),
    Pr("cn.quam", "Which offering do thou, O God, deign in all things to make blessed ✠, approved ✠, ratified ✠, reasonable and acceptable: that it may become for us the Body ✠ and Blood ✠ of thy most beloved Son, our Lord Jesus Christ."),
    Pr("cn.pridie", "Who, the day before he suffered, took bread into his holy and venerable hands, and with his eyes lifted up to heaven, unto thee, God, his almighty Father, giving thanks to thee, he blessed ✠, broke, and gave it to his disciples, saying: Take, and eat ye all of this:"),
    Pr("cn.hoc", "FOR THIS IS MY BODY."),
    R("cn.r3", "Genuflecting, he adores the Sacred Host; rising, he elevates it for the people to see; replacing it on the corporal, he again genuflects in adoration. From now until the ablution of the fingers, he keeps thumb and forefinger joined.", { postures: ["genuflect", "genuflect"] }),
    Pr("cn.simili", "In like manner, after he had supped, taking also this precious chalice into his holy and venerable hands, again giving thanks to thee, he blessed ✠, and gave it to his disciples, saying: Take, and drink ye all of this:"),
    Pr("cn.calix1", "FOR THIS IS THE CHALICE OF MY BLOOD, OF THE NEW AND ETERNAL COVENANT:"),
    Pr("cn.mysterium", "THE MYSTERY OF FAITH:"),
    Pr("cn.calix2", "WHICH SHALL BE SHED FOR YOU AND FOR MANY UNTO THE REMISSION OF SINS."),
    Pr("cn.haec", "As often as ye shall do these things, ye shall do them in memory of me."),
    R("cn.r4", "Genuflecting, he adores the Precious Blood; rising, he elevates the chalice for the people to see; replacing it, he again genuflects in adoration.", { postures: ["genuflect", "genuflect"] }),
    Pr("cn.unde", "Wherefore, O Lord, we thy servants, and likewise thy holy people, calling to mind the blessed Passion of the same Christ thy Son our Lord, his Resurrection from the dead, and his glorious Ascension into heaven, offer unto thy most excellent Majesty, from thine own gifts and bounty, a pure ✠ Victim, a holy ✠ Victim, a spotless ✠ Victim, the holy Bread ✠ of eternal life, and the Chalice ✠ of everlasting salvation."),
    Pr("cn.supra", "Upon which deign to look with a favourable and serene countenance, and to accept them, as thou didst deign to accept the gifts of thy just servant Abel, and the sacrifice of our Patriarch Abraham, and that which thy high priest Melchisedech offered to thee, a holy sacrifice, a spotless victim."),
    Pr("cn.supplices", "We humbly beseech thee, almighty God, command these to be carried by the hands of thy holy Angel to thine altar on high, in the sight of thy divine Majesty, that as many of us as, by partaking at this altar, shall receive the most sacred Body ✠ and Blood ✠ of thy Son, may be filled ✠ with every heavenly blessing and grace. Through the same Christ our Lord. Amen.", { postures: ["bow-profound"] }),
    Pr("cn.memento2", "Remember also, O Lord, thy servants and handmaids N. and N., who have gone before us with the sign of faith, and sleep the sleep of peace. To these, O Lord, and to all who rest in Christ, grant, we beseech thee, a place of refreshment, light and peace. Through the same Christ our Lord. Amen."),
    Pr("cn.nobis", "To us sinners also, thy servants, who hope in the multitude of thy mercies, deign to grant some part and fellowship with thy holy Apostles and Martyrs: with John, Stephen, Matthias, Barnabas, Ignatius, Alexander, Marcellinus, Peter, Felicity, Perpetua, Agatha, Lucy, Agnes, Cecilia, Anastasia, and with all thy Saints; into whose company admit us, we beseech thee, not weighing our merits, but freely granting us pardon. Through Christ our Lord.", { postures: ["strike-breast"] }),
    Pr("cn.perquem", "Through whom, O Lord, thou dost always create, sanctify ✠, quicken ✠, bless ✠, and bestow upon us all these good things."),
    Pr("cn.peripsum", "Through ✠ him, and with ✠ him, and in ✠ him, is unto thee, God the Father ✠ almighty, in the unity of the Holy ✠ Ghost, all honour and glory."),
    P("cn.end1", "World without end."), S("cn.end2", "Amen."),
  ],
  edits: [
    { id: "cn-options", type: "optional", target: "cn.te", options: ["I", "II", "III", "IV"],
      replacement: [nh("cn-options.h", "Eucharistic Prayer"), nr("cn-options.1", "The Roman Canon becomes Eucharistic Prayer I. Or Eucharistic Prayer II, III or IV.")],
      source: src(`${OM62}, Canon Missae (the only Canon)`, `${OM70}, Preces eucharisticae I–IV`, "1968/1970", "Prayers II–IV were approved in 1968. The Roman Canon itself survives as Prayer I.") },
    { id: "cn-silent", type: "rubric", target: "cn.r1", phrase: " silently",
      source: src(`${RS62}, Canon`, `${OM70}: said aloud`, TAA(10)) },
    ...[2, 3].map((k) => ({ id: `cn-te-cross${k}`, type: "rubric", target: "cn.te", phrase: "✠", occurrence: k,
      source: src(`${OM62}, Te igitur`, `${OM70}, Prex eucharistica I: one sign of the Cross`, TAA(11)) })),
    { id: "cn-saints1", type: "shortened", target: "cn.communicantes",
      phrase: "James, John, Thomas, James, Philip, Bartholomew, Matthew, Simon and Thaddeus; Linus, Cletus, Clement, Sixtus, Cornelius, Cyprian, Lawrence, Chrysogonus, John and Paul, Cosmas and Damian, ",
      mark: "ad lib.",
      source: src(`${OM62}, Communicantes`, `${OM70}, Prex eucharistica I (names in brackets)`, "1970", "These names may be omitted.") },
    ...[["cn.communicantes", " Through the same Christ our Lord. Amen."], ["cn.hanc", " Through Christ our Lord. Amen."], ["cn.memento2", " Through the same Christ our Lord. Amen."]]
      .map(([target, phrase], i) => ({ id: `cn-concl${i}`, type: "shortened", target, phrase,
        source: src(`${OM62}, Canon`, `${OM70}, Prex eucharistica I (conclusion in brackets)`, "1970", "This conclusion may be omitted.") })),
    ...[1, 2, 3, 4, 5].map((k) => ({ id: `cn-quam-cross${k}`, type: "rubric", target: "cn.quam", phrase: "✠", occurrence: k,
      source: src(`${OM62}, Quam oblationem`, `${OM70}, Prex eucharistica I`, TAA(11)) })),
    { id: "cn-pridie-cross", type: "rubric", target: "cn.pridie", phrase: "✠",
      source: src(`${OM62}, Qui pridie`, `${OM70}, Prex eucharistica I`, TAA(11)) },
    { id: "cn-tradetur", type: "added", target: "cn.hoc",
      replacement: [n("cn-tradetur.1", "…WHICH WILL BE GIVEN UP FOR YOU.")],
      source: src(`${OM62}, words of consecration`, `${OM70}, words of the Lord in every Eucharistic Prayer`, "1970", "“quod pro vobis tradetur” added to the words over the bread.") },
    { id: "cn-host-genuflect", type: "posture", target: "cn.r3", icon: "genuflect", action: "remove",
      source: src(`${RS62}, elevation of the Host`, `${OM70}: one genuflection, after showing the Host`, TAA(7)) },
    { id: "cn-digits", type: "rubric", target: "cn.r3", phrase: " From now until the ablution of the fingers, he keeps thumb and forefinger joined.",
      source: src(`${RS62}, after the consecration`, ABSENT, TAA(12)) },
    { id: "cn-simili-cross", type: "rubric", target: "cn.simili", phrase: "✠",
      source: src(`${OM62}, Simili modo`, `${OM70}, Prex eucharistica I`, TAA(11)) },
    { id: "cn-mysterium", type: "moved", target: "cn.mysterium", destination: "cn.r4",
      source: src(`${OM62}, inside the words over the chalice`, `${OM70}: said by the priest after the consecration, introducing the acclamation`, "1970") },
    { id: "cn-acclamation", type: "added", target: "cn.mysterium",
      replacement: [
        nh("cn-acclamation.h", "Acclamation · one of three"),
        n("cn-acclamation.1", "We proclaim your death, O Lord, and confess your resurrection, until you come."),
        n("cn-acclamation.2", "Or: As often as we eat this bread and drink this cup, we proclaim your death, O Lord, until you come."),
        n("cn-acclamation.3", "Or: Saviour of the world, save us, who by your cross and resurrection have set us free."),
      ],
      source: src("—", `${OM70}, acclamation after the consecration`, "1970") },
    { id: "cn-haec", type: "rewritten", target: "cn.haec",
      replacement: [n("cn-haec.1", "DO THIS IN MEMORY OF ME.")],
      source: src(`${OM62}, Haec quotiescumque`, `${OM70}, Hoc facite in meam commemorationem`, "1970") },
    { id: "cn-chalice-genuflect", type: "posture", target: "cn.r4", icon: "genuflect", action: "remove",
      source: src(`${RS62}, elevation of the chalice`, `${OM70}: one genuflection, after showing the chalice`, TAA(7)) },
    ...[1, 2, 3, 4, 5].map((k) => ({ id: `cn-unde-cross${k}`, type: "rubric", target: "cn.unde", phrase: "✠", occurrence: k,
      source: src(`${OM62}, Unde et memores`, `${OM70}, Prex eucharistica I`, TAA(11)) })),
    ...[1, 2].map((k) => ({ id: `cn-supplices-cross${k}`, type: "rubric", target: "cn.supplices", phrase: "✠", occurrence: k,
      source: src(`${OM62}, Supplices te rogamus`, `${OM70}, Prex eucharistica I`, TAA(11), "The priest still signs himself at “filled with every heavenly blessing”.") })),
    { id: "cn-supplices-concl", type: "shortened", target: "cn.supplices", phrase: " Through the same Christ our Lord. Amen.",
      source: src(`${OM62}, Supplices`, `${OM70}, Prex eucharistica I (conclusion in brackets)`, "1970", "This conclusion may be omitted.") },
    { id: "cn-saints2", type: "shortened", target: "cn.nobis",
      phrase: "Ignatius, Alexander, Marcellinus, Peter, Felicity, Perpetua, Agatha, Lucy, Agnes, Cecilia, Anastasia, ",
      mark: "ad lib.",
      source: src(`${OM62}, Nobis quoque peccatoribus`, `${OM70}, Prex eucharistica I (names in brackets)`, "1970", "These names may be omitted.") },
    { id: "cn-nobis-breast", type: "posture", target: "cn.nobis", icon: "strike-breast", action: "remove",
      source: src(`${RS62}, Nobis quoque`, `${OM70}: no striking of the breast prescribed`, "1970", "", "medium") },
    ...[1, 2, 3].map((k) => ({ id: `cn-perquem-cross${k}`, type: "rubric", target: "cn.perquem", phrase: "✠", occurrence: k,
      source: src(`${OM62}, Per quem haec omnia`, `${OM70}, Prex eucharistica I`, TAA(11)) })),
    ...[1, 2, 3, 4, 5].map((k) => ({ id: `cn-peripsum-cross${k}`, type: "rubric", target: "cn.peripsum", phrase: "✠", occurrence: k,
      source: src(`${OM62}, Per ipsum (five signs with the Host)`, `${OM70}: Host and chalice raised together, without signs`, IO("48f")) })),
  ],
};

const communion = {
  id: "communion", title: "The Communion", initial: "O",
  blocks: [
    P("co.oremus", "Let us pray. Taught by saving precepts, and following the divine instruction, we make bold to say:"),
    R("co.r1", "The Priest alone says the Lord's Prayer; the server answers the last petition."),
    Pr("co.pater", "Our Father, who art in heaven, hallowed be thy name; thy kingdom come; thy will be done on earth as it is in heaven. Give us this day our daily bread; and forgive us our trespasses, as we forgive those who trespass against us. And lead us not into temptation."),
    S("co.pater2", "But deliver us from evil."), P("co.pater3", "Amen."),
    Pr("co.libera", "Deliver us, we beseech thee, O Lord, from all evils, past, present and to come; and by the intercession of the blessed and glorious ever-Virgin Mary, Mother of God, together with thy blessed Apostles Peter and Paul, and Andrew, and all the Saints, graciously grant peace in our days, that, aided by the help of thy mercy, we may be ever free from sin and safe from all disturbance. Through the same Jesus Christ thy Son, our Lord, who liveth and reigneth with thee in the unity of the Holy Ghost, God,"),
    R("co.r2", "He signs himself with the paten and kisses it, then breaks the Host over the chalice."),
    P("co.wwe", "World without end."), S("co.wwe2", "Amen."),
    P("co.pax", "The peace ✠ of the Lord be ✠ always with ✠ you."), S("co.pax2", "And with thy spirit."),
    Pr("co.commixtio", "May this mingling and consecration of the Body and Blood of our Lord Jesus Christ be for us who receive it unto life everlasting. Amen."),
    Pr("co.agnus", "Lamb of God, who takest away the sins of the world, have mercy on us. Lamb of God, who takest away the sins of the world, have mercy on us. Lamb of God, who takest away the sins of the world, grant us peace.", { postures: ["strike-breast"] }),
    R("co.r3", "Bowing, with hands joined upon the altar, he says silently:"),
    Pr("co.dixisti", "O Lord Jesus Christ, who saidst to thine Apostles: Peace I leave you, my peace I give you: look not upon my sins, but upon the faith of thy Church; and deign to grant her peace and unity according to thy will: who livest and reignest, God, world without end. Amen."),
    Pr("co.fili", "O Lord Jesus Christ, Son of the living God, who by the will of the Father, with the cooperation of the Holy Ghost, hast by thy death given life to the world: deliver me by this thy most sacred Body and Blood from all my iniquities and from every evil; make me always cleave to thy commandments, and never suffer me to be separated from thee: who with the same God the Father and the Holy Ghost livest and reignest, God, world without end. Amen."),
    Pr("co.perceptio", "Let not the partaking of thy Body, O Lord Jesus Christ, which I, though unworthy, presume to receive, turn to my judgement and condemnation; but through thy loving kindness may it be to me a safeguard of mind and body, and a healing remedy: who with God the Father, in the unity of the Holy Ghost, livest and reignest, God, world without end. Amen."),
    R("co.r4", "He genuflects, rises, and says:"),
    Pr("co.panem", "I will take the Bread of heaven, and call upon the name of the Lord."),
    R("co.r5", "Striking his breast, he says three times:"),
    P("co.dns1", "Lord, I am not worthy that thou shouldst come under my roof; say but the word, and my soul shall be healed.", { postures: ["strike-breast"] }),
    P("co.dns2", "Lord, I am not worthy that thou shouldst come under my roof; say but the word, and my soul shall be healed.", { postures: ["strike-breast"] }),
    P("co.dns3", "Lord, I am not worthy that thou shouldst come under my roof; say but the word, and my soul shall be healed.", { postures: ["strike-breast"] }),
    P("co.corpus", "May the Body of our Lord Jesus Christ keep my soul unto life everlasting. Amen.", { postures: ["sign-cross"] }),
    Pr("co.quid", "What shall I render to the Lord for all the things that he hath rendered to me? I will take the chalice of salvation, and I will call upon the name of the Lord. Praising I will call upon the Lord: and I shall be saved from my enemies."),
    P("co.sanguis", "May the Blood of our Lord Jesus Christ keep my soul unto life everlasting. Amen.", { postures: ["sign-cross"] }),
    R("co.r6", "Turning to the people, holding a Host over the ciborium, he says:"),
    P("co.ecce", "Behold the Lamb of God, behold him who taketh away the sins of the world."),
    R("co.r7", "Then he says three times: Lord, I am not worthy… To each communicant, making the sign of the Cross with the Host, he says:"),
    P("co.tibi", "May the Body of our Lord Jesus Christ keep thy soul unto life everlasting. Amen."),
    R("co.r8", "Taking the ablutions, he says:"),
    Pr("co.quod", "What we have taken with our mouth, O Lord, may we receive with a pure mind; and from a gift in time may it become for us a remedy for eternity."),
    Pr("co.corpustuum", "May thy Body, O Lord, which I have received, and thy Blood which I have drunk, cleave to my inmost being; and grant that no stain of sin may remain in me, whom these pure and holy sacraments have refreshed: who livest and reignest world without end. Amen."),
    R("co.r9", "He reads the Communion verse; then he kisses the altar and, turning to the people, says: The Lord be with you; and reads the Postcommunion of the day."),
  ],
  edits: [
    { id: "co-pater-all", type: "rubric", target: "co.r1", phrase: "The Priest alone says the Lord's Prayer; the server answers the last petition.",
      source: src(`${OM62}, Pater noster`, `${OM70}: said by all`, IO("48g")) },
    { id: "co-libera-saints", type: "shortened", target: "co.libera",
      phrase: " past, present and to come; and by the intercession of the blessed and glorious ever-Virgin Mary, Mother of God, together with thy blessed Apostles Peter and Paul, and Andrew, and all the Saints,",
      source: src(`${OM62}, Libera nos`, `${OM70}, Libera nos`, "1970") },
    { id: "co-libera-end", type: "shortened", target: "co.libera",
      phrase: " Through the same Jesus Christ thy Son, our Lord, who liveth and reigneth with thee in the unity of the Holy Ghost, God,",
      source: src(`${OM62}, Libera nos`, `${OM70}, Libera nos`, "1970", "The ending becomes: as we await the blessed hope and the coming of our Saviour, Jesus Christ.") },
    { id: "co-dixisti", type: "moved", target: "co.dixisti", destination: "co.libera",
      source: src(`${OM62}: after the Agnus Dei, said silently`, `${OM70}: before the Pax, said aloud`, "1970") },
    { id: "co-doxology", type: "added", target: "co.libera",
      replacement: [
        n("co-doxology.1", "…as we await the blessed hope and the coming of our Saviour, Jesus Christ.", "P"),
        n("co-doxology.2", "For yours are the kingdom, and the power, and the glory, for ever.", "R"),
      ],
      source: src("—", `${OM70}, embolism and acclamation`, "1970") },
    { id: "co-paten", type: "rubric", target: "co.r2", phrase: "He signs himself with the paten and kisses it, then",
      source: src(`${RS62}, Libera nos`, ABSENT, "1970", "", "medium") },
    ...[1, 2, 3].map((k) => ({ id: `co-pax-cross${k}`, type: "rubric", target: "co.pax", phrase: "✠", occurrence: k,
      source: src(`${OM62}, Pax Domini (three crosses with a particle over the chalice)`, `${OM70}: no signs`, "1970", "", "medium") })),
    { id: "co-sign-peace", type: "added", target: "co.pax2",
      replacement: [n("co-sign-peace.1", "Offer one another peace.", "D"), nr("co-sign-peace.2", "All exchange a sign of peace according to local custom.")],
      source: src("Kiss of peace among the clergy at High Mass only", `${OM70}, Ritus pacis`, "1970", "The invitation is optional (“pro opportunitate”).") },
    { id: "co-commixtio", type: "shortened", target: "co.commixtio", phrase: " and consecration",
      source: src(`${OM62}, Haec commixtio`, `${OM70}, Haec commixtio`, "1970") },
    { id: "co-agnus-breast", type: "posture", target: "co.agnus", icon: "strike-breast", action: "remove",
      source: src(`${RS62}, Agnus Dei`, `${OM70}: no striking of the breast prescribed`, "1970", "", "medium") },
    { id: "co-dixisti-silent", type: "rubric", target: "co.r3", phrase: " silently",
      source: src(`${RS62}, Domine Iesu Christe, qui dixisti`, `${OM70}: said aloud`, "1970") },
    { id: "co-prep-prayers", type: "optional", target: "co.fili", options: ["I", "II"],
      replacement: [nr("co-prep-prayers.1", "The priest says this prayer or the next, not both.")],
      source: src(`${OM62}: both prayers said`, `${OM70}: one or the other`, "1970") },
    { id: "co-panem", type: "removed", target: "co.r4", targets: ["co.panem"],
      source: src(`${OM62}, Panem caelestem accipiam`, ABSENT, "1970") },
    { id: "co-ecce-moved", type: "moved", target: "co.ecce", destination: "co.perceptio",
      source: src(`${OM62}: shown to the people after the priest's Communion`, `${OM70}: before the priest's Communion, followed by “Lord, I am not worthy” said once by all`, "1970") },
    { id: "co-dns2", type: "repetition", target: "co.dns2", phrase: "Lord, I am not worthy that thou shouldst come under my roof; say but the word, and my soul shall be healed.",
      source: src(`${OM62}, Domine, non sum dignus (×3 by the priest)`, `${OM70}: said once, by priest and people together`, "1970") },
    { id: "co-dns3", type: "repetition", target: "co.dns3", phrase: "Lord, I am not worthy that thou shouldst come under my roof; say but the word, and my soul shall be healed.",
      source: src(`${OM62}, Domine, non sum dignus (×3 by the priest)`, `${OM70}: said once, by priest and people together`, "1970") },
    { id: "co-dns-breast", type: "rubric", target: "co.r5", phrase: "Striking his breast, he says three times:",
      source: src(`${RS62}, Domine, non sum dignus`, `${OM70}: said once, no striking of the breast prescribed`, "1970", "", "medium") },
    { id: "co-corpus", type: "rewritten", target: "co.corpus",
      replacement: [n("co-corpus.1", "May the Body of Christ keep me for eternal life.", "P")],
      source: src(`${OM62}, Corpus Domini nostri…`, `${OM70}, Corpus Christi custodiat me`, "1970") },
    { id: "co-quid", type: "removed", target: "co.quid",
      source: src(`${OM62}, Quid retribuam; Calicem salutaris accipiam`, ABSENT, "1970") },
    { id: "co-sanguis", type: "rewritten", target: "co.sanguis",
      replacement: [n("co-sanguis.1", "May the Blood of Christ keep me for eternal life.", "P")],
      source: src(`${OM62}, Sanguis Domini nostri…`, `${OM70}, Sanguis Christi custodiat me`, "1970") },
    { id: "co-people-thrice", type: "rubric", target: "co.r7", phrase: "Then he says three times: Lord, I am not worthy… ",
      source: src(`${RS62}, Communion of the faithful`, `${OM70}: said once, before the priest's Communion`, "1970") },
    { id: "co-tibi", type: "rewritten", target: "co.tibi",
      replacement: [n("co-tibi.1", "The Body of Christ.", "P"), n("co-tibi.2", "Amen.", "R")],
      source: src(`${OM62}, Corpus Domini nostri… custodiat animam tuam`, `${OM70}, Corpus Christi — Amen`, IO("48i"), "The communicant now answers Amen; the priest no longer signs with the Host.") },
    { id: "co-corpustuum", type: "removed", target: "co.corpustuum",
      source: src(`${OM62}, Corpus tuum, Domine`, ABSENT, "1970", "Quod ore sumpsimus is kept.") },
    { id: "co-kiss", type: "rubric", target: "co.r9", phrase: " he kisses the altar and,",
      source: src(`${RS62}, Postcommunion`, "Altar kissed only at the beginning and end of Mass", TAA(8)) },
  ],
};

const dismissal = {
  id: "dismissal", title: "The Dismissal and Last Gospel", initial: "I",
  blocks: [
    P("di.dv", "The Lord be with you."), S("di.dv2", "And with thy spirit."),
    P("di.ite", "Go, the Mass is ended."), S("di.ite2", "Thanks be to God."),
    R("di.r1", "Bowing before the middle of the altar, with hands joined upon it, he says silently:"),
    Pr("di.placeat", "May the homage of my service be pleasing to thee, O holy Trinity: and grant that the sacrifice which I, though unworthy, have offered in the sight of thy Majesty, may be acceptable to thee, and through thy mercy obtain forgiveness for me and for all those for whom I have offered it. Through Christ our Lord. Amen."),
    R("di.r2", "He kisses the altar and, turning to the people, blesses them:"),
    P("di.bless", "May almighty God bless you, the Father, and the Son, ✠ and the Holy Ghost.", { postures: ["sign-cross"] }),
    S("di.bless2", "Amen."),
    R("di.r3", "At the Gospel side he says:"),
    P("di.lg1", "The Lord be with you."), S("di.lg2", "And with thy spirit."),
    P("di.lg3", "The beginning ✠ of the holy Gospel according to St. John.", { postures: ["sign-cross"] }),
    S("di.lg4", "Glory be to thee, O Lord."),
    X("di.jn1", "In the beginning was the Word, and the Word was with God, and the Word was God. The same was in the beginning with God. All things were made by him: and without him was made nothing that was made. In him was life, and the life was the light of men. And the light shineth in darkness, and the darkness did not comprehend it."),
    X("di.jn2", "There was a man sent from God, whose name was John. This man came for a witness, to give testimony of the light, that all men might believe through him. He was not the light, but was to give testimony of the light. That was the true light, which enlighteneth every man that cometh into this world. He was in the world, and the world was made by him, and the world knew him not. He came unto his own, and his own received him not. But as many as received him, he gave them power to be made the sons of God, to them that believe in his name. Who are born, not of blood, nor of the will of the flesh, nor of the will of man, but of God."),
    X("di.jn3", "And the Word was made flesh, and dwelt among us, (and we saw his glory, the glory as it were of the only begotten of the Father,) full of grace and truth.", { postures: ["genuflect"] }),
    S("di.jn4", "Thanks be to God."),
  ],
  edits: [
    { id: "di-bless-moved", type: "moved", target: "di.bless", destination: "di.dv2",
      source: src(`${OM62}: blessing after Ite, missa est`, `${OM70}: blessing before the dismissal`, TAA(16)) },
    { id: "di-bless2-moved", type: "moved", target: "di.bless2", destination: "di.bless",
      source: src(`${OM62}: blessing after Ite, missa est`, `${OM70}: blessing before the dismissal`, TAA(16)) },
    { id: "di-placeat", type: "removed", target: "di.r1", targets: ["di.placeat"],
      source: src(`${OM62}, Placeat tibi, sancta Trinitas`, ABSENT, "1967/1970", "Said silently from 1967 (Tres abhinc annos 16); absent from 1970.") },
    { id: "di-kiss", type: "rubric", target: "di.r2", phrase: "He kisses the altar and, turning to the people, blesses them:",
      source: src(`${RS62}, blessing`, `${OM70}: the altar is kissed after the dismissal`, "1970", "", "medium") },
    { id: "di-lastgospel", type: "removed", target: "di.r3",
      targets: ["di.lg1", "di.lg2", "di.lg3", "di.lg4", "di.jn1", "di.jn2", "di.jn3", "di.jn4"],
      source: src(`${OM62}, Last Gospel (John 1:1–14)`, ABSENT, IO("48j"), "With it goes the genuflection at “And the Word was made flesh”.") },
  ],
};

export const missal = { sections: [foot, kyrie, readings, creed, offertory, preface, canon, communion, dismissal] };
